In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv('concrete.csv')

In [3]:
type(data)

pandas.core.frame.DataFrame

In [4]:
data.head()

Cement (component 1)(kg in a m^3 mixture)  \
0                                      540.0   
1                                      540.0   
2                                      332.5   
3                                      332.5   
4                                      198.6   

   Blast Furnace Slag (component 2)(kg in a m^3 mixture)  \
0                                                0.0       
1                                                0.0       
2                                              142.5       
3                                              142.5       
4                                              132.4       

   Fly Ash (component 3)(kg in a m^3 mixture)  \
0                                         0.0   
1                                         0.0   
2                                         0.0   
3                                         0.0   
4                                         0.0   

   Water  (component 4)(kg in a m^3 mixture)  \
0                                      162.0   
1                                      162.0   
2                                      228.0   
3                                      228.0   
4                                      192.0   

   Superplasticizer (component 5)(kg in a m^3 mixture)  \
0                                                2.5     
1                                                2.5     
2                                                0.0     
3                                                0.0     
4                                                0.0     

   Coarse Aggregate  (component 6)(kg in a m^3 mixture)  \
0                                             1040.0      
1                                             1055.0      
2                                              932.0      
3                                              932.0      
4                                              978.4      

   Fine Aggregate (component 7)(kg in a m^3 mixture)  Age (day)  \
0                                              676.0         28   
1                                              676.0         28   
2                                              594.0        270   
3                                              594.0        365   
4                                              825.5        360   

   Concrete compressive strength(MPa, megapascals)   
0                                             79.99  
1                                             61.89  
2                                             40.27  
3                                             41.05  
4                                             44.30

In [5]:
data.tail()

Cement (component 1)(kg in a m^3 mixture)  \
1025                                      276.4   
1026                                      322.2   
1027                                      148.5   
1028                                      159.1   
1029                                      260.9   

      Blast Furnace Slag (component 2)(kg in a m^3 mixture)  \
1025                                              116.0       
1026                                                0.0       
1027                                              139.4       
1028                                              186.7       
1029                                              100.5       

      Fly Ash (component 3)(kg in a m^3 mixture)  \
1025                                        90.3   
1026                                       115.6   
1027                                       108.6   
1028                                         0.0   
1029                                        78.3   

      Water  (component 4)(kg in a m^3 mixture)  \
1025                                      179.6   
1026                                      196.0   
1027                                      192.7   
1028                                      175.6   
1029                                      200.6   

      Superplasticizer (component 5)(kg in a m^3 mixture)  \
1025                                                8.9     
1026                                               10.4     
1027                                                6.1     
1028                                               11.3     
1029                                                8.6     

      Coarse Aggregate  (component 6)(kg in a m^3 mixture)  \
1025                                              870.1      
1026                                              817.9      
1027                                              892.4      
1028                                              989.6      
1029                                              864.5      

      Fine Aggregate (component 7)(kg in a m^3 mixture)  Age (day)  \
1025                                              768.3         28   
1026                                              813.4         28   
1027                                              780.0         28   
1028                                              788.9         28   
1029                                              761.5         28   

      Concrete compressive strength(MPa, megapascals)   
1025                                             44.28  
1026                                             31.18  
1027                                             23.70  
1028                                             32.77  
1029                                             32.40

In [7]:
data.describe()

Cement (component 1)(kg in a m^3 mixture)  \
count                                1030.000000   
mean                                  281.167864   
std                                   104.506364   
min                                   102.000000   
25%                                   192.375000   
50%                                   272.900000   
75%                                   350.000000   
max                                   540.000000   

       Blast Furnace Slag (component 2)(kg in a m^3 mixture)  \
count                                        1030.000000       
mean                                           73.895825       
std                                            86.279342       
min                                             0.000000       
25%                                             0.000000       
50%                                            22.000000       
75%                                           142.950000       
max                                           359.400000       

       Fly Ash (component 3)(kg in a m^3 mixture)  \
count                                 1030.000000   
mean                                    54.188350   
std                                     63.997004   
min                                      0.000000   
25%                                      0.000000   
50%                                      0.000000   
75%                                    118.300000   
max                                    200.100000   

       Water  (component 4)(kg in a m^3 mixture)  \
count                                1030.000000   
mean                                  181.567282   
std                                    21.354219   
min                                   121.800000   
25%                                   164.900000   
50%                                   185.000000   
75%                                   192.000000   
max                                   247.000000   

       Superplasticizer (component 5)(kg in a m^3 mixture)  \
count                                        1030.000000     
mean                                            6.204660     
std                                             5.973841     
min                                             0.000000     
25%                                             0.000000     
50%                                             6.400000     
75%                                            10.200000     
max                                            32.200000     

       Coarse Aggregate  (component 6)(kg in a m^3 mixture)  \
count                                        1030.000000      
mean                                          972.918932      
std                                            77.753954      
min                                           801.000000      
25%                                           932.000000      
50%                                           968.000000      
75%                                          1029.400000      
max                                          1145.000000      

       Fine Aggregate (component 7)(kg in a m^3 mixture)    Age (day)  \
count                                        1030.000000  1030.000000   
mean                                          773.580485    45.662136   
std                                            80.175980    63.169912   
min                                           594.000000     1.000000   
25%                                           730.950000     7.000000   
50%                                           779.500000    28.000000   
75%                                           824.000000    56.000000   
max                                           992.600000   365.000000   

       Concrete compressive strength(MPa, megapascals)   
count                                       1030.000000  
mean                                          35.817961  
std                                           16.705742

In [8]:
data.isnull().any()

Cement (component 1)(kg in a m^3 mixture)                False
Blast Furnace Slag (component 2)(kg in a m^3 mixture)    False
Fly Ash (component 3)(kg in a m^3 mixture)               False
Water  (component 4)(kg in a m^3 mixture)                False
Superplasticizer (component 5)(kg in a m^3 mixture)      False
Coarse Aggregate  (component 6)(kg in a m^3 mixture)     False
Fine Aggregate (component 7)(kg in a m^3 mixture)        False
Age (day)                                                False
Concrete compressive strength(MPa, megapascals)          False
dtype: bool

In [9]:
#Since there is no null value there in the dataset,no need of fill the missing value

In [11]:
data

Cement (component 1)(kg in a m^3 mixture)  \
0                                         540.0   
1                                         540.0   
2                                         332.5   
3                                         332.5   
4                                         198.6   
5                                         266.0   
6                                         380.0   
7                                         380.0   
8                                         266.0   
9                                         475.0   
10                                        198.6   
11                                        198.6   
12                                        427.5   
13                                        190.0   
14                                        304.0   
15                                        380.0   
16                                        139.6   
17                                        342.0   
18                                        380.0   
19                                        475.0   
20                                        427.5   
21                                        139.6   
22                                        139.6   
23                                        139.6   
24                                        380.0   
25                                        380.0   
26                                        380.0   
27                                        342.0   
28                                        427.5   
29                                        475.0   
...                                         ...   
1000                                      141.9   
1001                                      297.8   
1002                                      321.3   
1003                                      366.0   
1004                                      279.8   
1005                                      252.1   
1006                                      164.6   
1007                                      155.6   
1008                                      160.2   
1009                                      298.1   
1010                                      317.9   
1011                                      287.3   
1012                                      325.6   
1013                                      355.9   
1014                                      132.0   
1015                                      322.5   
1016                                      164.2   
1017                                      313.8   
1018                                      321.4   
1019                                      139.7   
1020                                      288.4   
1021                                      298.2   
1022                                      264.5   
1023                                      159.8   
1024                                      166.0   
1025                                      276.4   
1026                                      322.2   
1027                                      148.5   
1028                                      159.1   
1029                                      260.9   

      Blast Furnace Slag (component 2)(kg in a m^3 mixture)  \
0                                                   0.0       
1                                                   0.0       
2                                                 142.5       
3                                                 142.5       
4                                                 132.4       
5                                                 114.0       
6                                                  95.0       
7                                                  95.0       
8                                                 114.0       
9                                                   0.0       
10                                                132.4       
11                                                132.4       
12                      

In [12]:
x=data.iloc[:,3:8].values
x

array([[ 162. ,    2.5, 1040. ,  676. ,   28. ],
       [ 162. ,    2.5, 1055. ,  676. ,   28. ],
       [ 228. ,    0. ,  932. ,  594. ,  270. ],
       ...,
       [ 192.7,    6.1,  892.4,  780. ,   28. ],
       [ 175.6,   11.3,  989.6,  788.9,   28. ],
       [ 200.6,    8.6,  864.5,  761.5,   28. ]])

In [13]:
y=data.iloc[:,8].values
y

array([79.99, 61.89, 40.27, ..., 23.7 , 32.77, 32.4 ])

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [15]:
x_train.shape 

(824, 5)

In [16]:
x_test.shape

(206, 5)

In [17]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [18]:
x_train

array([[ 0.4954066 , -1.05983651, -0.46017905, -0.64352249, -0.2880169 ],
       [ 0.21507763, -1.05983651,  0.85205772, -0.18717261, -0.2880169 ],
       [ 1.49991871, -0.02050666, -0.98121424, -0.62502182, -0.2880169 ],
       ...,
       [-1.09312419,  1.95757271, -0.37012359,  0.87353254, -0.2880169 ],
       [ 0.20106119, -1.05983651, -0.38813468, -1.34284786, -0.2880169 ],
       [ 0.4954066 , -1.05983651, -0.53994246, -0.70395802,  0.71554384]])

In [19]:
x_test

array([[ 0.84162878, -0.9604699 ,  1.90323484, -2.12762775, -0.61689118],
       [ 1.00758375, -0.9604699 , -0.24926722,  0.32662103, -0.55832916],
       [-0.8226625 ,  0.98258705, -0.42348051, -0.25447582,  0.67147326],
       ...,
       [-0.82740407,  0.12831201,  0.37015784,  0.24004678, -0.45584563],
       [ 0.60455025, -0.12294535, -1.06484353, -0.5535505 , -0.25087856],
       [ 0.24419089, -0.0391929 , -0.26604331,  1.1280887 , -0.61689118]])